spring.application.name=CiberShield

spring.datasource.username=ADMIN
spring.datasource.password=Casa2024#%$#


spring.datasource.url=jdbc:oracle:thin:@cibershield_high


spring.datasource.type=oracle.ucp.jdbc.PoolDataSourceImpl


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect