# Nombre de la aplicación
spring.application.name=CiberShield

# --- Configuración para Oracle Cloud Autonomous Database ---

# Leemos el usuario y la contraseña de tu archivo .env
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Esta es la URL de conexión correcta, usando el descriptor TNS que te dio Oracle
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gba9b0121f7a306_cibershield_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))

# Propiedades de seguridad que le dicen a Spring dónde encontrar los archivos del Wallet
# Estas leen las variables de tu archivo .env
spring.datasource.oracleucp.connection-properties.oracle.net.tns_admin=${PATH_TO_YOUR_WALLET}
spring.datasource.oracleucp.connection-properties.javax.net.ssl.keyStore=${PATH_TO_YOUR_WALLET}/keystore.jks
spring.datasource.oracleucp.connection-properties.javax.net.ssl.keyStorePassword=${WALLET_PASSWORD}
spring.datasource.oracleucp.connection-properties.javax.net.ssl.trustStore=${PATH_TO_YOUR_WALLET}/truststore.jks
spring.datasource.oracleucp.connection-properties.javax.net.ssl.trustStorePassword=${WALLET_PASSWORD}

# Configuración de JPA y Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update